# Uncomment the next line to define a global platform for your project
 platform :iOS, '9.0'

target 'app design' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  Pods for app design
 pod 'Alamofire
 pod 'SVProgressHUD'
pod 'GoogleMaps'
end
